[[worker]]

[worker.config]
id = "domain-name-toolkit"
enabled = true
timeout = 30
retries = 3
secret = "4a765ee6fdc11cec148cbcc183b97c47"
[worker.local_source]
packages = [ "./domain_name_toolkit",]
